sudo: required
language: php
dist: trusty

services:
- mysql

php:
- 7.2

addons:
  chrome: stable
before_install:
- mysql -e 'CREATE DATABASE codeweek;'

install:
- cp .env.travis .env
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- travis_retry npm install
- npm run prod
- php artisan migrate:fresh --seed

before_script:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &
- php artisan serve &

script:
- php artisan dusk

notifications:
  email:
    - alainvd@gmail.com